version: '2'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=smyllo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3340:3306

  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300:11300

  nginx:
    container_name: ci_nginx
    image: nginx:latest
    links:
        - php
    volumes:
      - ./devops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www/ci
      - /vendor
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.composer:/root/.composer
      - /tmpfs

  php:
    container_name: ci_php
    build: devops/php
    working_dir: /var/www/ci
    environment:
      CI_ENV: development
    volumes_from:
        - nginx
    links:
        - db
    mem_limit: 2000000000
